#!/usr/bin/env python3
"""Renders the generated files for install/install.sh. Standard library only.

Subcommands (all print one line per file: wrote, updated, unchanged, skipped, or would write):

  settings-merge  --settings PATH --hooks hooks.json --root ROOT [--output-style NAME]
  settings-remove --settings PATH [--output-style NAME]   (restores *.acc-backup when it matches)
  output-style    --root ROOT --out PATH
  managed-block   --root ROOT --out PATH [--import FILE] [--remove]
                  (the block holds AGENTS.md's body, or just "@FILE" with --import)
  manifest        --out PATH --root ROOT --scope S --target T --mode MODE
                  (entries on stdin, one "kind<TAB>path" per line)

Every generated file starts with MARKER. A file that exists without it is never touched.
--dry-run reports what would change and writes nothing.
"""

import argparse
import datetime
import json
import os
import sys

MARKER = "<!-- generated by ai-coding-config; edits are overwritten on the next install -->"
BLOCK_BEGIN = "<!-- ai-coding-config:begin -->"
BLOCK_END = "<!-- ai-coding-config:end -->"
TAG = "ai-coding-config:"
STYLE_NAME = "Plain Technical English"


# --- frontmatter -------------------------------------------------------------

def split_frontmatter(text):
    """Returns (dict, body). Handles the YAML subset these files use."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end < 0:
        return {}, text
    raw = text[4:end]
    body = text[end + 4:]
    body = body[1:] if body.startswith("\n") else body
    return parse_yaml_subset(raw), body


def unquote(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_yaml_subset(raw):
    data = {}
    key = None
    folded = False
    for line in raw.split("\n"):
        if not line.strip():
            continue
        if line.startswith(" ") or line.startswith("\t"):
            stripped = line.strip()
            if key is None:
                continue
            if stripped.startswith("- "):
                if not isinstance(data.get(key), list):
                    data[key] = []
                data[key].append(unquote(stripped[2:]))
            elif folded or isinstance(data.get(key), str):
                data[key] = (data.get(key, "") + " " + stripped).strip()
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        folded = value in (">", ">-", "|", "|-")
        if folded or value == "":
            data[key] = ""
        elif value in ("true", "false"):
            data[key] = value == "true"
        elif value.startswith("[") and value.endswith("]"):
            data[key] = [unquote(v) for v in value[1:-1].split(",") if v.strip()]
        else:
            data[key] = unquote(value)
    return data


# --- file writing ------------------------------------------------------------

def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def write_generated(path, content, dry_run):
    """Writes a marker-led file. Refuses to replace a file that is not ours."""
    if os.path.exists(path):
        existing = read(path)
        if MARKER not in existing.split("\n", 8)[:8]:
            print("skipped %s (exists and was not generated by ai-coding-config)" % path)
            return False
        if existing == content:
            print("unchanged %s" % path)
            return True
        verb = "updated"
    else:
        verb = "wrote"
    if dry_run:
        print("would write %s" % path)
        return True
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print("%s %s" % (verb, path))
    return True


def style_body(root):
    return split_frontmatter(read(os.path.join(root, "style", "communication.md")))


# --- subcommands -------------------------------------------------------------

def cmd_settings_merge(args):
    settings = {}
    if os.path.exists(args.settings):
        text = read(args.settings)
        if text.strip():
            settings = json.loads(text)
    ours = json.loads(read(args.hooks).replace("__ACC_ROOT__", args.root))["hooks"]
    hooks = settings.setdefault("hooks", {})

    def is_ours(group):
        entries = group.get("hooks") or []
        return bool(entries) and all(
            str(h.get("statusMessage", "")).startswith(TAG) for h in entries)

    for event, groups in ours.items():
        kept = [g for g in hooks.get(event, []) if not is_ours(g)]
        hooks[event] = kept + groups
    if args.output_style and "outputStyle" not in settings:
        settings["outputStyle"] = args.output_style
    content = json.dumps(settings, indent=2) + "\n"
    existing = read(args.settings) if os.path.exists(args.settings) else None
    if existing == content:
        print("unchanged %s" % args.settings)
        return
    if args.dry_run:
        print("would write %s" % args.settings)
        return
    os.makedirs(os.path.dirname(args.settings) or ".", exist_ok=True)
    with open(args.settings, "w", encoding="utf-8") as fh:
        fh.write(content)
    print("%s %s" % ("updated" if existing is not None else "wrote", args.settings))


def is_ours(group):
    entries = group.get("hooks") or []
    return bool(entries) and all(
        str(h.get("statusMessage", "")).startswith(TAG) for h in entries)


def cmd_settings_remove(args):
    if not os.path.exists(args.settings):
        print("absent %s" % args.settings)
        return
    settings = json.loads(read(args.settings) or "{}")
    hooks = settings.get("hooks") or {}
    for event in list(hooks):
        hooks[event] = [g for g in hooks[event] if not is_ours(g)]
        if not hooks[event]:
            del hooks[event]
    if not hooks and "hooks" in settings:
        del settings["hooks"]
    if args.output_style and settings.get("outputStyle") == args.output_style:
        del settings["outputStyle"]
    backup = args.settings + ".acc-backup"
    restore = None
    if os.path.exists(backup):
        try:
            if json.loads(read(backup) or "{}") == settings:
                restore = read(backup)
        except ValueError:
            pass
    if args.dry_run:
        print("would %s %s" % ("restore" if restore is not None else "update", args.settings))
        return
    if restore is not None:
        with open(args.settings, "w", encoding="utf-8") as fh:
            fh.write(restore)
        os.remove(backup)
        print("restored %s from backup" % args.settings)
    elif settings:
        with open(args.settings, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(settings, indent=2) + "\n")
        print("updated %s" % args.settings)
    else:
        os.remove(args.settings)
        print("removed %s" % args.settings)


def cmd_output_style(args):
    meta, body = style_body(args.root)
    front = ["---", "name: %s" % STYLE_NAME,
             "description: %s" % json.dumps(meta.get("description", "")),
             "keep-coding-instructions: true", "---"]
    content = "\n".join(front) + "\n" + MARKER + "\n\n" + body.strip() + "\n"
    write_generated(args.out, content, args.dry_run)


def remove_managed_block(args):
    if not os.path.exists(args.out):
        print("absent %s" % args.out)
        return
    existing = read(args.out)
    if BLOCK_BEGIN not in existing or BLOCK_END not in existing:
        print("unchanged %s (no managed block)" % args.out)
        return
    start = existing.index(BLOCK_BEGIN)
    end = existing.index(BLOCK_END) + len(BLOCK_END)
    content = (existing[:start].rstrip("\n") + "\n" + existing[end:].lstrip("\n")).strip("\n")
    if content == "":
        if args.dry_run:
            print("would remove %s" % args.out)
            return
        os.remove(args.out)
        print("removed %s" % args.out)
        return
    if args.dry_run:
        print("would update %s" % args.out)
        return
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(content + "\n")
    print("updated %s" % args.out)


def cmd_managed_block(args):
    if args.remove:
        remove_managed_block(args)
        return
    if args.import_file:
        text = "@" + args.import_file
    else:
        _, body = split_frontmatter(read(os.path.join(args.root, "AGENTS.md")))
        lines = body.strip().split("\n")
        if lines and lines[0].startswith("# "):
            lines = lines[1:]
        text = "\n".join(lines).strip()
    block = "\n".join([BLOCK_BEGIN, MARKER, text, BLOCK_END])
    existing = read(args.out) if os.path.exists(args.out) else ""
    if args.import_file and BLOCK_BEGIN not in existing and \
            ("@" + args.import_file) in [line.strip() for line in existing.split("\n")]:
        print("unchanged %s (already imports %s)" % (args.out, args.import_file))
        return
    if BLOCK_BEGIN in existing and BLOCK_END in existing:
        start = existing.index(BLOCK_BEGIN)
        end = existing.index(BLOCK_END) + len(BLOCK_END)
        content = existing[:start] + block + existing[end:]
    elif existing.strip():
        content = existing.rstrip("\n") + "\n\n" + block + "\n"
    else:
        content = block + "\n"
    if content == existing:
        print("unchanged %s" % args.out)
        return
    if args.dry_run:
        print("would write %s" % args.out)
        return
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(content)
    print("%s %s" % ("updated" if existing else "wrote", args.out))


def cmd_manifest(args):
    """Writes the manifest, merged with any existing one so that a rerun keeps the
    entries an earlier install recorded."""
    files = []
    if os.path.exists(args.out):
        try:
            previous = json.loads(read(args.out))
            files = [f for f in previous.get("files", []) if isinstance(f, dict)]
        except ValueError:
            pass
    seen = set((f["kind"], f["path"]) for f in files)
    for line in sys.stdin.read().split("\n"):
        if "\t" in line:
            kind, _, path = line.partition("\t")
            if (kind, path) not in seen:
                files.append({"kind": kind, "path": path})
                seen.add((kind, path))
    data = {
        "version": 1,
        "root": args.root,
        "scope": args.scope,
        "target": args.target,
        "mode": args.mode,
        "installedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "files": files,
    }
    content = json.dumps(data, indent=2) + "\n"
    if args.dry_run:
        print("would write %s" % args.out)
        return
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(content)
    print("wrote %s" % args.out)


def main(argv):
    parser = argparse.ArgumentParser(prog="render.py")
    sub = parser.add_subparsers(dest="command", required=True)

    def add(name, fn, *options):
        p = sub.add_parser(name)
        p.add_argument("--dry-run", action="store_true")
        for opt in options:
            p.add_argument(opt, required=True)
        p.set_defaults(fn=fn)
        return p

    p = add("settings-merge", cmd_settings_merge, "--settings", "--hooks", "--root")
    p.add_argument("--output-style", default="")
    p = add("settings-remove", cmd_settings_remove, "--settings")
    p.add_argument("--output-style", default="")
    add("output-style", cmd_output_style, "--root", "--out")
    p = add("managed-block", cmd_managed_block, "--root", "--out")
    p.add_argument("--remove", action="store_true")
    p.add_argument("--import", dest="import_file", default="")
    add("manifest", cmd_manifest, "--out", "--root", "--scope", "--target", "--mode")
    args = parser.parse_args(argv)
    args.fn(args)


if __name__ == "__main__":
    main(sys.argv[1:])
