#!/usr/bin/env bash
# Removes an ai-coding-config install, using the manifest install/install.sh wrote.
#
#   install/uninstall.sh --user [--dry-run]
#   install/uninstall.sh --project <path> [--dry-run]
#
# Removes only what this config placed: links that point into it, copies and generated
# files it recorded, its tagged hook groups in settings.json, the managed CLAUDE.md and AGENTS.md blocks,
# the git hooks, and the git config entry. A settings backup is restored when the stripped
# settings still match it.

set -u
root=$(cd "$(dirname "$0")/.." && pwd -P)
render="$root/install/lib/render.py"

scope=''; project=''; dry_run=0
while [ $# -gt 0 ]; do
  case "$1" in
    --user) scope=user ;;
    --project) scope=project; project=${2:-}; shift ;;
    --dry-run) dry_run=1 ;;
    -h|--help) sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "uninstall.sh: unknown option '$1'" >&2; exit 2 ;;
  esac
  shift
done
case "$scope" in
  user) target="$HOME/.claude" ;;
  project)
    [ -n "$project" ] && [ -d "$project" ] || { echo "uninstall.sh: --project needs an existing path" >&2; exit 2; }
    project=$(cd "$project" && pwd -P); target="$project/.claude" ;;
  *) echo "uninstall.sh: choose --user or --project <path>" >&2; exit 2 ;;
esac

manifest="$target/acc-manifest.json"
[ -f "$manifest" ] || { echo "uninstall.sh: no manifest at $manifest; nothing to remove"; exit 0; }
. "$root/hooks/lib/json.sh"
m=$(cat "$manifest")
dry() { [ "$dry_run" = 1 ]; }
say() { printf '%s\n' "$*"; }
remove() {
  if dry; then say "would remove $1"; else rm -rf "$1"; say "removed $1"; fi
}
dry_flag=''; dry && dry_flag='--dry-run'

i=0
while :; do
  kind=$(json_get "$m" files "$i" kind); path=$(json_get "$m" files "$i" path)
  [ -n "$kind" ] || break
  i=$((i + 1))
  path="$(dirname "$target")/$path"  # manifest paths are relative to the directory that holds .claude
  case "$kind" in
    symlink)
      if [ -L "$path" ]; then
        case "$(readlink "$path")" in
          "$root"/*) remove "$path" ;;
          *) say "kept $path (links elsewhere)" ;;
        esac
      fi ;;
    copy)
      [ -e "$path" ] && remove "$path" ;;
    generated)
      if [ -f "$path" ]; then
        if head -n 8 "$path" | grep -q 'generated by ai-coding-config'; then remove "$path"
        else say "kept $path (not generated by ai-coding-config)"; fi
      fi ;;
    managed-block)
      python3 "$render" managed-block --remove --root "$root" --out "$path" $dry_flag ;;
    settings)
      python3 "$render" settings-remove --settings "$path" --output-style "Plain Technical English" $dry_flag ;;
    git-config)
      if dry; then say "would unset git config ai-coding-config.gate"
      else (cd "$project" && git config --unset ai-coding-config.gate 2>/dev/null); say "unset git config ai-coding-config.gate"; fi ;;
  esac
done

# Directories left empty, then the manifest itself.
for dir in skills rules agents output-styles; do
  d="$target/$dir"
  [ -d "$d" ] && [ -z "$(ls -A "$d")" ] && remove "$d"
done
remove "$manifest"
[ -d "$target" ] && [ -z "$(ls -A "$target")" ] && remove "$target"
say "Done."
exit 0
